### ISSUE TITLE
CUDA unavailable leads to error

### ISSUE THREAD

**Issue by javanasse** [hugofloresgarcia/vampnet#3]
I ran into this error on my 2021 M1 Macbook Pro. 

```console 
>>> python app.py --args.load conf/interface.yml --Interface.device cpu
loading wavebeat from ./models/wavebeat.pth
Traceback (most recent call last):
  File "/vampnet/vampnet/app.py", line 22, in <module>
    interface = Interface()
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/argbind/argbind.py", line 159, in cmd_func
    return func(*cmd_args, **kwargs)
  File "/vampnet/vampnet/vampnet/interface.py", line 92, in __init__
    self.beat_tracker = WaveBeat(wavebeat_ckpt)
  File "/vampnet/vampnet/vampnet/beats.py", line 206, in __init__
    model = dsTCNModel.load_from_checkpoint(ckpt_path)
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1520, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 62, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/lightning_fabric/utilities/cloud_io.py", line 51, in _load
    return torch.load(f, map_location=map_location)  # type: ignore[arg-type]
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/pickle.py", line 1253, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/opt/anaconda3/envs/vampnet-env/lib/python3.9/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

Fixed this by changing [this line](https://github.com/hugofloresgarcia/vampnet/blob/df7025d6bb4e5e9c9af901a0ce56f7525ed9089b/vampnet/beats.py#L206) to:
```python
model = dsTCNModel.load_from_checkpoint(ckpt_path, map_location=torch.device(device))
```

**Comment by hugofloresgarcia** [comment]
Nice catch, thanks!
